<?php
$data = $this->session->get('value');
echo "<section style='background-color: #eee;'>
<div class='container py-5'>
  <div class='row justify-content-center mb-3'>
    <div class='col-md-12 col-xl-10'>
      <div class='card shadow-0 border rounded-3'>";
foreach ($data['docs'] as $value) {
  echo "<div class='card-body'><div class='row'>
               <div class='col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0'>
               <div class='bg-image hover-zoom ripple rounded ripple-surface'>
                <img src='//covers.openlibrary.org/b/id/$value[cover_i]-M.jpg'
                  class='w-100' />
              </div>
            </div>
            <div class='col-md-6 col-lg-6 col-xl-6'>
              <h4>$value[title]</h4>
               </div>";
  foreach ($value['author_name'] as $value1) {
    echo " <p>$value1<p>";
  }
  echo "</div><div class='col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start'>
  <div class='d-flex flex-column mt-4'>";
  echo $this->tag->linkTo(["index/fullpage/?isbn=" . $value['isbn'][0], "Detail", "class" => "btn btn-primary"]);
  echo " </div></div></div>";
}
echo "</div></div></div>";
